name = "bubble"
main = "src/src/index.js"
compatibility_date = "2023-08-23"
workers_dev = true
compatibility_flags = [ "nodejs_compat" ]

[[routes]]
pattern = "api.bit123.finance"
zone_name = "bit123.finance"
custom_domain = true

[[d1_databases]]
database_name = "bubble-db"
binding = "DATABASE"
database_id = "02960b44-c6f0-430d-9f5a-992b9b6d780c"

[[kv_namespaces]]
binding = "KV"
id = "6a99a897c17e4edcb20ca86b1425f1f0"
preview_id = "db994901e833489e83fee1cbadb63040"
